pid = /tmp/rinkhals/stunnel.pid
cert = /useremain/home/rinkhals/printer_data/certs/moonraker.cert
key = /useremain/home/rinkhals/printer_data/certs/moonraker.key

foreground = no
client = no
;debug = info
;output = /var/log/rinkhals/stunnel.log

[default_ui]
accept = 443
connect = 80

[mjpg_streamer]
accept = 8443
connect = 8080

[fluidd]
accept = 4443
connect = 4408

[mainsail]
accept = 5443
connect = 4409

[moonraker]
# Moonraker can also handle SSL internally, hence the cert/key locations (it expects them there).
# If one also enables SSL in moonraker (by choosing a server.ssl_port in moonraker.custom.conf)
# the ports here (accept) and in the Moonraker configuration must not collide, though they can be used in tandem.
accept = 7143
connect = 7125

[rinkhals_webui]
accept = 1443
connect = 1414
